## Reading data for England

In [1]:
import pandas as pd

df = pd.read_csv('../Extacted data/Pharm stats /Pharm_England_2021_2025.csv')
df.head(2)

,YEAR_MONTH,REGIONAL_OFFICE_NAME,REGIONAL_OFFICE_CODE,BNF_CHEMICAL_SUBSTANCE,CHEMICAL_SUBSTANCE_BNF_DESCR,QUANTITY,ITEMS,TOTAL_QUANTITY,ADQUSAGE,NIC,ACTUAL_COST
0,202101,EAST OF ENGLAND,Y61,0401010AC,Sodium oxybate,9720.0,23.0,11340.0,0.0,22680.00,21169.66950
1,202101,EAST OF ENGLAND,Y61,0401010AD,Melatonin,432989.0,13612.0,848532.0,0.0,507959.54,473801.90184

In [2]:
# have null value in column 'CHEMICAL_SUBSTANCE_BNF_DESCR'
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 97795 entries, 0 to 97794
Data columns (total 11 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   YEAR_MONTH                    97795 non-null  int64
 1   REGIONAL_OFFICE_NAME          97795 non-null  str
 2   REGIONAL_OFFICE_CODE          97795 non-null  str
 3   BNF_CHEMICAL_SUBSTANCE        97795 non-null  str
 4   CHEMICAL_SUBSTANCE_BNF_DESCR  81951 non-null  str
 5   QUANTITY                      97795 non-null  float64
 6   ITEMS                         97795 non-null  float64
 7   TOTAL_QUANTITY                97795 non-null  float64
 8   ADQUSAGE                      97795 non-null  float64
 9   NIC                           97795 non-null  float64
 10  ACTUAL_COST                   97795 non-null  float64
dtypes: float64(6), int64(1), str(4)
memory usage: 12.0 MB

## Fill in nulls in CHEMICAL_SUBSTANCE_BNF_DESCR column from BNF_CHEMICAL_SUBSTANCE

In [3]:
df['CHEMICAL_SUBSTANCE_BNF_DESCR'] = df['CHEMICAL_SUBSTANCE_BNF_DESCR'].fillna(df['BNF_CHEMICAL_SUBSTANCE'])

## Dropping columns

In [4]:
df = df.drop(columns=['REGIONAL_OFFICE_CODE','BNF_CHEMICAL_SUBSTANCE','TOTAL_QUANTITY','QUANTITY','ADQUSAGE'])

In [5]:
df.head()

,YEAR_MONTH,REGIONAL_OFFICE_NAME,CHEMICAL_SUBSTANCE_BNF_DESCR,ITEMS,NIC,ACTUAL_COST
0,202101,EAST OF ENGLAND,Sodium oxybate,23.0,22680.00,21169.66950
1,202101,EAST OF ENGLAND,Melatonin,13612.0,507959.54,473801.90184
2,202101,EAST OF ENGLAND,Chloral hydrate,105.0,10411.30,9711.62549
3,202101,EAST OF ENGLAND,Cloral betaine,5.0,388.06,361.74905
4,202101,EAST OF ENGLAND,Clomethiazole edisilate,1.0,30.00,27.93492

## Changing type and names of columns

In [6]:
df['YEAR_MONTH'] = pd.to_datetime(df['YEAR_MONTH'], format='%Y%m').dt.strftime('%Y-%m')

In [7]:
df = df.rename(columns={
    'YEAR_MONTH': 'date',
    'REGIONAL_OFFICE_NAME': 'region',
    'CHEMICAL_SUBSTANCE_BNF_DESCR': 'chemical_substance',
    'ITEMS': 'items',
    'NIC': 'net_cost ',
    'ACTUAL_COST': 'actual_cost'
})

In [8]:
df.head()

,date,region,chemical_substance,items,net_cost,actual_cost
0,2021-01,EAST OF ENGLAND,Sodium oxybate,23.0,22680.00,21169.66950
1,2021-01,EAST OF ENGLAND,Melatonin,13612.0,507959.54,473801.90184
2,2021-01,EAST OF ENGLAND,Chloral hydrate,105.0,10411.30,9711.62549
3,2021-01,EAST OF ENGLAND,Cloral betaine,5.0,388.06,361.74905
4,2021-01,EAST OF ENGLAND,Clomethiazole edisilate,1.0,30.00,27.93492

## Filtering antidepressants from the list

In [9]:
df['chemical_substance'].nunique()

264

In [10]:
for item in sorted(df['chemical_substance'].unique()):
    print(item)

Acamprosate calcium
Agomelatine
Almotriptan
Alprazolam
Amantadine hydrochloride
Amisulpride
Amitriptyline hydrochloride
Amobarbital
Amobarbital sodium
Amoxapine
Analgesics with anti-emetics
Apomorphine hydrochloride
Apomorphine hydrochloride hemihydrate
Aprepitant
Aripiprazole
Asenapine
Aspirin
Aspirin and caffeine
Aspirin combined preparations
Atogepant
Atomoxetine hydrochloride
Benperidol
Benzatropine mesilate
Betahistine hydrochloride
Biperiden hydrochloride
Botulinum toxin type A
Brivaracetam
Bromazepam
Buprenorph hydrochloride/naloxone hydrochloride
Buprenorphine
Buprenorphine hydrochloride
Bupropion hydrochloride
Buspirone hydrochloride
Butobarbital
Cabergoline
Caffeine
Caffeine citrate
Cannabidiol
Carbamazepine
Carbidopa
Cariprazine
Cenobamate
Chloral hydrate
Chlordiazepoxide hydrochloride
Chlorpromazine hydrochloride
Chlorprothixene
Cinnarizine
Citalopram hydrobromide
Citalopram hydrochloride
Clobazam
Clomethiazole
Clomethiazole edisilate
Clomipramine hydrochloride
Clonazepam
Clonidine hydrochloride
Cloral betaine
Clozapine
Co-beneldopa (Benserazide/levodopa)
Co-careldopa (Carbidopa/levodopa)
Co-codamol (Codeine phosphate/paracetamol)
Co-codaprin (Codeine phosphate/aspirin)
Co-dydramol (Dihydrocodeine/paracetamol)
Co-proxamol (Dextropropoxyphene hydrochloride/paracetamol)
Codeine phosphate
Cyclizine hydrochloride
Cyclizine lactate
Cytisinicline
Daridorexant
Dexamfetamine sulfate
Diamorphine hydrochloride (Systemic)
Diazepam
Dihydrocodeine tartrate
Dimenhydrinate/cinnarizine
Dipipanone hydrochloride
Disulfiram
Domperidone
Donepezil hydrochloride
Dosulepin hydrochloride
Doxepin
Doxylamine succinate/pyridoxine hydrochloride
Duloxetine hydrochloride
Eletriptan
Entacapone
Erenumab
Erenumab (old)
Ergotamine tartrate
Escitalopram
Eslicarbazepine acetate
Eszopiclone
Ethosuximide
Felbamate
Fentanyl
Flunarizine dihydrochloride
Fluoxetine hydrochloride
Flupentixol decanoate
Flupentixol hydrochloride
Fluphenazine decanoate
Fluphenazine hydrochloride
Flurazepam hydrochloride
Fluvoxamine maleate
Fosphenytoin sodium
Fremanezumab
Frovatriptan
Gabapentin
Gabapentin (Neuropathic Pain)
Galantamine
Galcanezumab
Granisetron
Granisetron hydrochloride
Guanfacine
Haloperidol
Haloperidol decanoate
Hydromorphone hydrochloride
Hyoscine
Hyoscine hydrobromide
Imipramine hydrochloride
Isocarboxazid
Isometheptene mucate
Ketamine hydrochloride
Lacosamide
Lamotrigine
Levetiracetam
Levodopa
Levodopa/carbidopa/entacapone
Levomepromazine hydrochloride
Levomepromazine maleate
Lisdexamfetamine dimesylate
Lithium carbonate
Lithium citrate
Lofepramine hydrochloride
Loprazolam mesilate
Lorazepam
Lormetazepam
Lurasidone
Meclozine hydrochloride
Melatonin
Melperone hydrochloride
Memantine hydrochloride
Meprobamate
Meptazinol hydrochloride
Mesuximide
Methadone hydrochloride
Methylphenidate hydrochloride
Metoclopramide hydrochloride
Mianserin hydrochloride
Midazolam hydrochloride
Midazolam maleate
Mirtazapine
Moclobemide
Modafinil
Morphine (Opium Tincture)
Morphine hydrochloride
Morphine sulfate
Morphine tartrate and cyclizine tartrate
Nabilone
Nalmefene
Naltrexone hydrochloride
Naltrexone/bupropion
Naratriptan hydrochloride
Nefazodone hydrochloride
Nefopam hydrochloride
Netupitant/palonosetron hydrochloride
Nicotine
Nicotine bitartrate
Nitrazepam
Nortriptyline
Olanzapine
Olanzapine embonate
Ondansetron hydrochloride
Opicapone
Orlistat
Orphenadrine hydrochloride
Other non-opioid analgesic preparations
Oxazepam
Oxcarbazepine
Oxitriptan
Oxycodone hydrochloride
Oxycodone hydrochloride/naloxone hydrochloride
Paliperidone
Papaveretum
Paracetamol
Paracetamol and caffeine
Paracetamol and ibuprofen
Paracetamol and phenylephrine hydrochloride
Paracetamol combined preparations
Paraldehyde
Paroxetine hydrochloride
Pentazocine hydrochloride
Perampanel
Pergolide mesilate
Pericyazine
Perphenazine
Pethidine hydrochloride
Phenelzine sulfate
Phenobarbital
Phenobarbital sodium
Phenytoin
Phenytoin sodium
Pimozide
Piracetam
Pitolisant hydrochloride
Pizotifen malate
Pramipexole
Pregabalin
Primidone
Prochlorperazine maleate
Prochlorperazine mesilate
Procyclidine hydrochloride
Promazine hydrochloride
Promethazine teoclate
Quetiapine
Rasagiline mesilate
Reboxetine
Riluzole
Rimegepant
Risperidone
Rivastigmine
Rizatriptan
Ropinirole hydrochloride
Rotigotine
Rufinamide
Safinamide
Secobarbital sodium
Selegiline hydrochloride
Sertraline hydrochloride
Sodium oxybate
Sodium valproate
Stiripentol
Sulpiride
Sultiame
Sumatriptan succinate
Sumatriptan succinate/Naproxen sodium
Tafamidis
Tapentadol
Tapentadol hydrochloride
Tapentadol phosphate
Tapentadol phosphate (old)
Temazepam
Tetrabenazine
Thioridazine
Tiagabine
Tolcapone
Tolfenamic acid
Topiramate
Tramadol hydrochloride
Tranylcypromine sulfate
Trazodone hydrochloride
Trifluoperazine
Trihexyphenidyl hydrochloride
Trimipramine maleate
Tryptophan
Valproic acid
Varenicline tartrate
Venlafaxine
Vigabatrin
Vortioxetine
Ziprasidone hydrochloride
Zolmitriptan
Zolpidem tartrate
Zonisamide
Zopiclone
Zuclopenthixol acetate
Zuclopenthixol decanoate
Zuclopenthixol hydrochloride

In [11]:
antidepressants = [
    'Agomelatine', 'Amitriptyline hydrochloride', 'Amoxapine', 
    'Bupropion hydrochloride', 'Citalopram hydrobromide', 'Citalopram hydrochloride',
    'Clomipramine hydrochloride', 'Dosulepin hydrochloride', 'Doxepin',
    'Duloxetine hydrochloride', 'Escitalopram', 'Fluoxetine hydrochloride',
    'Flupentixol decanoate', 'Flupentixol hydrochloride', 'Fluvoxamine maleate',
    'Imipramine hydrochloride', 'Isocarboxazid', 'Lofepramine hydrochloride',
    'Mianserin hydrochloride', 'Mirtazapine', 'Moclobemide',
    'Nefazodone hydrochloride', 'Nortriptyline', 'Oxitriptan',
    'Paroxetine hydrochloride', 'Phenelzine sulfate', 'Reboxetine',
    'Sertraline hydrochloride', 'Tranylcypromine sulfate', 'Trazodone hydrochloride',
    'Trimipramine maleate', 'Tryptophan', 'Venlafaxine', 'Vortioxetine'
]

anxiolytics = [
    'Alprazolam', 'Amobarbital', 'Amobarbital sodium', 'Bromazepam',
    'Buspirone hydrochloride', 'Butobarbital', 'Chloral hydrate',
    'Chlordiazepoxide hydrochloride', 'Clobazam', 'Clomethiazole',
    'Clomethiazole edisilate', 'Clonazepam', 'Cloral betaine', 'Daridorexant',
    'Diazepam', 'Eszopiclone', 'Flurazepam hydrochloride', 'Loprazolam mesilate',
    'Lorazepam', 'Lormetazepam', 'Meprobamate', 'Melatonin',
    'Midazolam hydrochloride', 'Midazolam maleate', 'Nitrazepam', 'Oxazepam',
    'Paraldehyde', 'Phenobarbital', 'Phenobarbital sodium', 'Pregabalin',
    'Promethazine teoclate', 'Secobarbital sodium', 'Sodium oxybate',
    'Temazepam', 'Zolpidem tartrate', 'Zopiclone'
]

# filter both groups
df_filtered = df[df['chemical_substance'].isin(antidepressants + anxiolytics)].copy()

# create new group column
df_filtered['group'] = df_filtered['chemical_substance'].apply(
    lambda x: 'Antidepressant' if x in antidepressants else 'Anxiolytics'
)

print(df_filtered.shape)
print(df_filtered['group'].value_counts())

(26790, 7)
group
Antidepressant    14622
Anxiolytics       12168
Name: count, dtype: int64

In [12]:
df_filtered.head()

,date,region,chemical_substance,items,net_cost,actual_cost,group
0,2021-01,EAST OF ENGLAND,Sodium oxybate,23.0,22680.00,21169.66950,Anxiolytics
1,2021-01,EAST OF ENGLAND,Melatonin,13612.0,507959.54,473801.90184,Anxiolytics
2,2021-01,EAST OF ENGLAND,Chloral hydrate,105.0,10411.30,9711.62549,Anxiolytics
3,2021-01,EAST OF ENGLAND,Cloral betaine,5.0,388.06,361.74905,Anxiolytics
4,2021-01,EAST OF ENGLAND,Clomethiazole edisilate,1.0,30.00,27.93492,Anxiolytics

In [13]:
df_filtered['region'] = 'England'
df_filtered['items_1000'] = df_filtered['items']/1000
df_filtered = df_filtered.rename(columns={'region': 'country'})

In [14]:
# reorder columns
df_filtered = df_filtered[["date","country","group","chemical_substance","items_1000","items","actual_cost"]]
df_filtered.head()

,date,country,group,chemical_substance,items_1000,items,actual_cost
0,2021-01,England,Anxiolytics,Sodium oxybate,0.023,23.0,21169.66950
1,2021-01,England,Anxiolytics,Melatonin,13.612,13612.0,473801.90184
2,2021-01,England,Anxiolytics,Chloral hydrate,0.105,105.0,9711.62549
3,2021-01,England,Anxiolytics,Cloral betaine,0.005,5.0,361.74905
4,2021-01,England,Anxiolytics,Clomethiazole edisilate,0.001,1.0,27.93492

In [15]:
# save to csv
df_filtered.to_csv("England_antidepressants_and_anxiolytics_21_25.csv", index=False)

In [49]:
# convert to monthly period
df_filtered["date"] = pd.PeriodIndex(df_filtered["date"], freq="M")

# filter range
df_group = df_filtered[
    (df["date"] >= "2021-01") &
    (df["date"] <= "2025-12")
]

# group and sum
result = (
    df_group
    .groupby(["date"])["items_1000"]
    .sum()
    .reset_index()
)

result.head()

/var/folders/ym/cz6zsz_x4x1c2yp9gz_f1fb00000gn/T/ipykernel_10047/1254377405.py:5: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_group = df_filtered[

      date  items_1000
0  2021-01    8654.052
1  2021-02    8177.173
2  2021-03    9180.265
3  2021-04    8861.376
4  2021-05    8466.288